trigger:
  - main

pool:
  name: 'Self-Hosted-Agent'

variables:
  buildConfiguration: 'Release'
  nugetFeedName: 'ClassLibraryProject-Feed'
  packageOutputDir: '$(Build.ArtifactStagingDirectory)/nupkg'  # Explicit output directory

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringLibrary.csproj'  # Explicit path to your library project
    versioningScheme: 'ByPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    configuration: $(buildConfiguration)
    outputDir: $(packageOutputDir)  # Packages go here

- task: NuGetAuthenticate@1

- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(packageOutputDir)/*.nupkg'  # Explicit path to package
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(nugetFeedName)'