trigger:
- main  # Adjust based on your branch

pool:
  name: 'Self-Hosted-Agent'  # Ensure this matches your agent's name

variables:
  BuildConfiguration: 'Release'
  PackageVersion: '1.0.0'  # Update versioning as needed
  NuGetFeedUrl: 'https://pkgs.dev.azure.com/YOUR_ORG/YOUR_PROJECT/_packaging/YOUR_FEED/nuget/v3/index.json'
  PAT: $(lab4PAT)

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet build --configuration $(BuildConfiguration)
  displayName: 'Build Solution'

- script: dotnet pack --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(PackageVersion)
  displayName: 'Pack NuGet Package'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

- script: dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" --api-key $(PAT) --source $(NuGetFeedUrl) --skip-duplicate
  displayName: 'Push to Azure Artifacts'
