trigger:
  - main

pool:
  vmImage: 'windows-latest'  # Free Microsoft-hosted agent (replace later with self-hosted)

variables:
  buildConfiguration: 'Release'
  nugetFeedName: 'ClassLibraryProject-Feed'  # Match your feed name

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'ByPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    configuration: $(buildConfiguration)

- task: NuGetAuthenticate@1  # Authenticate with Azure Artifacts

- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(nugetFeedName)'