trigger:
  - main

pool:
  name: 'Self-Hosted-Agent'

variables:
  buildConfiguration: 'Release'
  nugetFeedName: 'ClassLibraryProjectFeed'
  packageOutputDir: '$(Build.ArtifactStagingDirectory)/nupkg'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringLibrary.csproj'
    versioningScheme: 'ByPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    configuration: $(buildConfiguration)
    outputDir: $(packageOutputDir)

- script: ls $(packageOutputDir)  # Debug step to verify .nupkg exists
  displayName: 'Verify NuGet Package'

- task: NuGetAuthenticate@1

- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(packageOutputDir)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'https://pkgs.dev.azure.com/crosari5/ClassLibraryProject/_packaging/ClassLibraryProjectFeed/nuget/v3/index.json'
    verbosity: 'Detailed'  # Added for better error logging